/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.stepniak.morenmodels.api

import net.stepniak.morenomodels.api.model.CreatedPhoto
import net.stepniak.morenomodels.api.model.NewPhoto
import net.stepniak.morenomodels.api.model.Photo
import net.stepniak.morenomodels.api.model.Photos
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.Request
import okhttp3.RequestBody
import okhttp3.RequestBody.Companion.toRequestBody
import org.junit.jupiter.api.assertThrows
import java.util.*
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class PhotosIntegrationTest : BaseIntegrationTest() {
    @Test
    fun `creates a new photo and returns upload URL`() {
        // given
        val createdPhoto = api.createPhoto(
            NewPhoto(
                photoSlug = "test-photo-${UUID.randomUUID()}"
            )
        )
        assertNotNull(createdPhoto.photoId)
        assertNotNull(createdPhoto.uploadUri)
        assertNotNull(createdPhoto.photoSlug)

        // when
        uploadPhotoFromDisk(createdPhoto, small = false)

        // then
        val receivedPhoto = api.getPhoto(createdPhoto.photoSlug)
        assertNotNull(receivedPhoto.photoId)
        assertNotNull(receivedPhoto.photoSlug)
        assertNotNull(receivedPhoto.uri)
        assertNotNull(receivedPhoto.version)
        // TODO: Parsing Photo Dimensions and automatic scaling is not implemented yet.
        assert(downloadPhoto(receivedPhoto) > 420)

        // cleanup
        api.archivePhoto(createdPhoto.photoSlug, delete = true)
    }

    @Test
    fun `erases a photo`() {
        // given
        val photo = createAndUploadPhoto()

        // when
        api.archivePhoto(photo.photoSlug, true)

        // then
        assertThrows<Exception> {
            api.getPhoto(photo.photoSlug)
        }
    }

    @Test
    fun `archives a photo`() {
        // given
        val photo = createAndUploadPhoto()

        // when
        api.archivePhoto(photo.photoSlug, false)

        // then
        assertTrue(api.getPhoto(photo.photoSlug).archived)

        // cleanup
        api.archivePhoto(photo.photoSlug, true)
    }

    @Test
    fun `lists photos and paginates`() {
        // given
        val pageSize = 5
        val numberOfCreatedPhotos = 11
        val createdPhotos = (1..11).map {
            createAndUploadPhoto(true)
        }.toList()

        var seenPages = 0
        var seenPhotos = 0
        var photos: Photos? = null
        // when
        do {
            photos = api.listPhotos(
                nextToken = photos?.metadata?.nextToken,
                pageSize,
                showArchived = null,
                modelSlug = null,
            );

            seenPages += 1
            seenPhotos += photos.items.size

            photos.items.forEach {
                assertNotNull(it.photoId)
                assertNotNull(it.photoSlug)
                assertNotNull(it.version)
                assertNotNull(it.uri)
            }

        } while (photos?.metadata?.nextToken != null)

        // then
        assertTrue {
            seenPhotos == numberOfCreatedPhotos
                    && seenPages == 3
        }

        // cleanup
        createdPhotos.forEach { api.archivePhoto(it.photoSlug, true) }
    }

    @Test
    fun `lists photos filtered by a model`() {
        // given
        val createdPhoto = createAndUploadPhoto(true)

        // when
        val photos = api.listPhotos(
            modelSlug = "non-existent-model",
            nextToken = null,
            showArchived = null,
            pageSize = null
        )

        // then
        assertTrue {
            photos.items.isEmpty()
        }

        // cleanup
        api.archivePhoto(createdPhoto.photoSlug, true)
    }

    private fun createAndUploadPhoto(small: Boolean = true): CreatedPhoto {
        val createdPhoto = api.createPhoto(NewPhoto(
            photoSlug = "test-photo-${UUID.randomUUID()}"
        ))

        uploadPhotoFromDisk(createdPhoto, small)
        return createdPhoto
    }

    private fun uploadPhotoFromDisk(createdPhoto: CreatedPhoto, small: Boolean = true) {
        val photoFilePath = if (small) "small-photo.png" else "big-photo.jpg"
        val photoMediaType = if (small) "image/png".toMediaType() else "image.jpg".toMediaType()


        val response = httpClient.newCall(
            Request.Builder()
                .url(createdPhoto.uploadUri.toURL())
                .method(
                    "PUT", body = RequestBody.javaClass.getResource(photoFilePath)
                        ?.readBytes()
                        ?.toRequestBody(photoMediaType)
                )
                .build()
        ).execute();

        assertTrue { response.isSuccessful }
    }

    private fun downloadPhoto(photo: Photo): Int {
        val response = httpClient.newCall(
            Request.Builder()
                .url(photo.uri.toURL())
                .method("GET", null)
                .build()
        ).execute();

        return response.body!!.bytes().size
    }
}
